### ISSUE TITLE
Add support for SASS

### ISSUE THREAD

**Issue by ruzicic** [edgeston/Planlife#1]
- [x] Add support for SASS for easier migration from the old app
- [x] Setup directory structure per personal preference
- [x] Migrate CSS/SCSS files

Docs: https://create-react-app.dev/docs/adding-a-sass-stylesheet/

**Comment by edgeston** [comment]
PR: [](https://github.com/edgeston/Planlife/pull/6)

**Comment by edgeston** [comment]
PR https://github.com/edgeston/Planlife/pull/6
