### ISSUE TITLE
Add homepage skeleton

### ISSUE THREAD

**Issue by ruzicic** [edgeston/Planlife#2]
- [x] Add `HomePage` component to be used as a container
- [x] Add `Sidebar` component placeholder inside `HomePage` 
- [x] Add `Header` sidebar component inside `HomePage` 
- [x] Add at least one component for the main section

**Comment by edgeston** [comment]
PR: https://github.com/edgeston/Planlife/pull/7

**Comment by edgeston** [comment]
Homepage Skeleton Completed
